orm:
  default:
    mysql: "root:9xz3jrd8wf@tcp(mysql:3306)/notification"
    redis: "redis:6379:0"
    locker: "default"
    local_cache: 1000
  streams_pool:
    redis: "redis:6379:1"

sms:
  twilio:
    sid: "sid"
    token: "token"
    from_number: "+123456789"

email:
  mailjet:
    api_key_public: "api_key_public"
    api_key_private: "api_key_private"

slack:
  bot_tokens:
    bot: "bot_token"

server:
  port: "8080"
