orm:
  default:
    mysql: root:9xz3jrd8wf@tcp(mysql:3306)/notification
    redis: redis:6379:0
    locker: default
    local_cache: 1000
  streams_pool:
    redis: redis:6379:1

sms:
  twilio:
    sid: sid
    token: token
    from_number: from

email:
  mailjet:
    api_key_public: public
    api_key_private: private

slack:
  bot_tokens:
    test_bot: token
